apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: spider2
    department: devops

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1

  selector:
    matchLabels:
      app: spider2
      department: devops

  template:
    metadata:
      labels:
        app: spider2
        department: devops
    spec:
      containers:
      - name: nginx-container
        image: httpd
        ports:
        - containerPort: 80
       