apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-hostpath-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mydata
    type: DirectoryOrCreate # Optional: creates the directory if it doesn't exist
